name: Deploy API

description: Deploy a generic API from a template.

branding:
  icon: truck
  color: blue

inputs:
  values-yaml:
    description: Path to the chart values file
    required: true
    type: string
  github-token:
    description: GitHub token
    required: true
    type: string
  kube-config-data:
    description: base64-encoded kubeconfig file data
    required: true
    type: string
  version:
    description: A specific version for the container image
    required: true
    type: string
  release-name:
    description: Release name for this deployment
    required: false
    type: string
    default: api
  namespace:
    description: Which namespace to release the charts to
    required: false
    type: string
    default: default

runs:
  using: composite
  steps:
    - name: Grab the values file
      uses: actions/checkout@v4
      with:
        path: values
        sparse-checkout: ${{ inputs.values-yaml }}
        sparse-checkout-cone-mode: false

    - name: Upgrade (or install) Helm chart
      uses: wahyd4/kubectl-helm-action@master
      with:
        args: |
          helm repo add ganiulis https://ganiulis.github.io/charts
          helm upgrade -i ${{ inputs.release-name }} ganiulis/api-template -f values/${{ inputs.values-yaml }} --set container.version=${{ inputs.version }} -n ${{ inputs.namespace }}
      env:
        KUBE_CONFIG_DATA: ${{ inputs.kube-config-data }}
